#!/bin/sh

user=$(ls /home)
echo "user = -----   $user   -----??   [Y/n]"

read ans
if [[ "$ans" =~ ^[Yy]$ || "$ans" == "" ]]; then
	continue
else
	echo ""
	echo ""
	echo ""
	echo "#####   Script has failed!   #####"
fi


dunstify "asdasdasd" -t 5000
